# Figure 1: variant-type AUROC

**Purpose.** Compare DNA- and protein-sequence model performance across the full benchmark and variant-type subgroups.

## Reproducibility contract

- **Run from:** the repository root.
- **Input:** `data/processed/clinvar_benchmark_updated.csv` (the full scored benchmark; not stored in GitHub).
- **Outputs:** `results/tables/figure_1_*.csv` and `results/figures/figure_1.svg`.
- **Randomness:** 1,000 stratified bootstrap replicates, seed 42.
- **Compute:** CPU; no model inference is performed.

## 1. Setup

In [1]:
from pathlib import Path
import pandas as pd

# Run this notebook from the repository root.
REPO_ROOT = Path.cwd()
DATA_DIR = REPO_ROOT / "data"
MODEL_SCORE_DIR = DATA_DIR / "model_scores"
RESULTS_DIR = REPO_ROOT / "results"
TABLE_DIR = RESULTS_DIR / "tables"
FIGURE_DIR = RESULTS_DIR / "figures"
SCORED_BENCHMARK_PATH = DATA_DIR / "processed" / "clinvar_benchmark_updated.csv"
RANDOM_SEED = 42

def read_table(path, required_columns=()):
    """Read a local table and verify that required columns are present."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}. See README.md.")
    frame = pd.read_parquet(path) if path.suffix == ".parquet" else pd.read_csv(
        path, low_memory=False, dtype={"#CHROM": str}
    )
    missing = sorted(set(required_columns) - set(frame.columns))
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")
    return frame

def validate_output_files(paths):
    """Verify that every expected output was created and is not empty."""
    for value in paths:
        path = Path(value)
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError(f"Expected output was not created: {path}")
    print(f"Validated {len(paths)} output file(s).")

FIGURE_DIR.mkdir(parents=True, exist_ok=True)
TABLE_DIR.mkdir(parents=True, exist_ok=True)

## 2. Load and inspect input

In [2]:
import pandas as pd

data = pd.read_csv(SCORED_BENCHMARK_PATH, low_memory=False, dtype={"#CHROM": str})
data

,#CHROM,POS,ID,REF,ALT,ClinVar_label,ClinVar_gold_stars,ClinVarName_refseq_ids,ClinVarName_AAPOS,ClinVarName_AAREF,...,DNASE_raw_abs,PROCAP_raw_abs,RNA_SEQ_raw_abs,SpliceJunction_raw_abs,SPLICE_SITES_raw_abs,SPLICE_SITE_USAGE_raw_abs,composite_quantile_score,composite_raw_score,splice_head_composite_quantile_score,aggregate_splice
0,1,930165,1164676,G,A,0.0,1.0,NM_001385641.1,207.0,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,930204,1170208,G,A,0.0,2.0,NM_001385641.1,220.0,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,930285,1165489,G,A,0.0,1.0,NM_001385641.1,247.0,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,930314,1170010,C,T,0.0,2.0,NM_001385641.1,257.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,930325,1168187,C,T,0.0,1.0,NM_001385641.1,260.0,I,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242127,Y,56960499,726033,A,G,0.0,1.0,NM_001304990.2,36.0,K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242128,Y,57084754,777848,C,G,0.0,2.0,NM_005638.6,109.0,V,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242129,Y,57087054,721652,T,C,0.0,2.0,NM_005638.6,127.0,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242130,Y,57190090,785714,G,A,0.0,1.0,NM_002186.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242131,Y,57191079,783917,C,T,0.0,2.0,NM_002186.3,191.0,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.columns

Index(['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'ClinVar_label',
       'ClinVar_gold_stars', 'ClinVarName_refseq_ids', 'ClinVarName_AAPOS',
       'ClinVarName_AAREF',
       ...
       'DNASE_raw_abs', 'PROCAP_raw_abs', 'RNA_SEQ_raw_abs',
       'SpliceJunction_raw_abs', 'SPLICE_SITES_raw_abs',
       'SPLICE_SITE_USAGE_raw_abs', 'composite_quantile_score',
       'composite_raw_score', 'splice_head_composite_quantile_score',
       'aggregate_splice'],
      dtype='object', length=121)

In [ ]:
import pandas as pd

score_cols = [
    'AlphaGenome_quantile', 'AlphaGenome_raw', 'Evo2_7B', 'DNABERT2',
    'PhyloP', 'GPN_MSA', 'ESM1b', 'ESM1v', 'ESM2',
    'PrimateAI_3D', 'AlphaMissense', 'PhyloGPN', 'Evo2_40B', 'Rule_based',
    'ntv3_pre_position_llr', 'ntv3_pre_seq_pllr', 'ntv3_post_position_llr',
    'ntv3_post_seq_pllr', 'ntv3_post_log2fc_max', 'vesm_score', 'gpnstar_v_llr'
]

group_cols = [c for c in data.columns if c.startswith('group: ')]

rows = []
for col in group_cols:
    mask = data[col] == 1
    subset = data[mask]
    row = {'Group': col, 'N': mask.sum()}
    for s in score_cols:
        row[s] = subset[s].notna().sum() if s in data.columns else None
    rows.append(row)

all_row = {'Group': 'ALL', 'N': len(data)}
for s in score_cols:
    all_row[s] = data[s].notna().sum() if s in data.columns else None
rows.append(all_row)

summary = pd.DataFrame(rows).set_index('Group')
summary

In [5]:
from sklearn.metrics import roc_auc_score

# Check NTv3 score direction
for col in ['ntv3_pre_position_llr', 'ntv3_pre_seq_pllr',
            'ntv3_post_position_llr', 'ntv3_post_seq_pllr', 'ntv3_post_log2fc_max', 'vesm_score', 'gpnstar_v_llr']:
    if col not in data.columns:
        print(f"{col}: not present; skipped")
        continue
    auc = roc_auc_score(
        data.loc[data[col].notna() & data['ClinVar_label'].notna(), 'ClinVar_label'],
        data.loc[data[col].notna() & data['ClinVar_label'].notna(), col]
    )
    print(f"{col}: AUROC={auc:.4f} ({'no flip needed' if auc > 0.5 else 'needs flip'})")

# Check the PrimateAI-3D missing rate for stop-gain variants
# sg = data[data["group: stop gain"] == 1]
# print(f"\nStop gain total: {len(sg)}")
# print(f"PrimateAI-3D non-null: {sg['PrimateAI_3D'].notna().sum()}")
# print(f"Missing rate: {sg['PrimateAI_3D'].isna().mean():.2%}")

ntv3_pre_position_llr: AUROC=0.0925 (needs flip)
ntv3_pre_seq_pllr: AUROC=0.0686 (needs flip)
ntv3_post_position_llr: AUROC=0.5343 (no flip needed)
ntv3_post_seq_pllr: AUROC=0.5140 (no flip needed)
ntv3_post_log2fc_max: AUROC=0.7087 (no flip needed)
vesm_score: AUROC=0.0158 (needs flip)

gpnstar_v_llr: AUROC=0.0265 (needs flip)

## 3. Compute AUROC and confidence intervals

In [6]:
import pandas as pd
from sklearn.metrics import roc_auc_score
import numpy as np
from tqdm import tqdm

N_BOOTSTRAPS = 1_000


def bootstrap_auc_ci(y, s, n_boot=N_BOOTSTRAPS, seed=42):
    y = np.asarray(y).astype(float)
    s = np.asarray(s).astype(float)

    # filter missing values
    valid = np.isfinite(y) & np.isfinite(s)
    y = y[valid].astype(int)
    s = s[valid]

    n = len(y)
    if n == 0 or len(np.unique(y)) < 2:
        return np.nan, np.nan, np.nan
    auc_hat = roc_auc_score(y, s)
    rng = np.random.default_rng(seed)
    class_indices = [np.flatnonzero(y == label) for label in (0, 1)]
    aucs = []
    for _ in range(n_boot):
        idx = np.concatenate([
            rng.choice(indices, size=len(indices), replace=True)
            for indices in class_indices
        ])
        aucs.append(roc_auc_score(y[idx], s[idx]))
    if len(aucs) < max(30, 0.5 * n_boot):
        return float(auc_hat), np.nan, np.nan
    lo, hi = np.percentile(aucs, [2.5, 97.5])
    return float(auc_hat), float(lo), float(hi)


# Model lists
dna_models = [
    'PhyloP', 'Evo2_7B', 'Evo2_40B', 'AlphaGenome_quantile', 'Rule_based',
    'GPN_MSA', 'PhyloGPN', 'DNABERT2',
    'ntv3_pre_position_llr',
    # 'ntv3_pre_seq_pllr',
    # 'ntv3_post_position_llr', 'ntv3_post_seq_pllr',
    'ntv3_post_log2fc_max', 'gpnstar_v_llr'
]

esm_models = ['ESM1b', 'ESM1v', 'ESM2', 'vesm_score']

protein_models = esm_models + ['AlphaMissense', 'PrimateAI_3D']

all_models = dna_models + protein_models

# Per-subgroup: (required_models, tool_list)
# required = must be non-null for variant to be included in subset
# tool_list = models to score in this subgroup
SUBGROUP_CONFIG = {
    'group: coding':                         (dna_models,              dna_models),
    'group: noncoding':                      (dna_models,              dna_models),
    'group: stop loss':                      (dna_models,              dna_models),
    'group: synonymous':                     (dna_models,              dna_models),
    "group: 5'UTR":                          (dna_models,              dna_models),
    "group: 3'UTR":                          (dna_models,              dna_models),
    "group: 3'UTR + RNA gene":               (dna_models,              dna_models),
    'group: splice':                         (dna_models,              dna_models),
    'group: intron (non-splice)':            (dna_models,              dna_models),
    'group: RNA gene':                       (dna_models,              dna_models),
    # DNA + all protein
    'group: missense':                       (all_models,              all_models),
    "group: missense + 3'UTR":               (all_models,              all_models),
    'group: missense + intron (non-splice)': (all_models,              all_models),
    'group: stop gain':                      (all_models,              all_models),
    # DNA + ESM only (AlphaMissense and PrimateAI_3D cannot score start loss)
    'group: start loss':                     (dna_models + esm_models, dna_models + esm_models),
}

# Models that do not need flipping because higher values indicate greater pathogenicity.
# NTv3-post log2FC is already in this orientation; NTv3-pre LLR is flipped below.
no_flip_models = {
    'PhyloP', 'DNABERT2',
    'AlphaMissense', 'PrimateAI_3D',
    'AlphaGenome_quantile', 'Rule_based',
    'ntv3_post_log2fc_max',
}

subgroups = list(SUBGROUP_CONFIG.keys())

results         = {group: {} for group in ['Overall'] + subgroups}
results_ci_low  = {group: {} for group in ['Overall'] + subgroups}
results_ci_high = {group: {} for group in ['Overall'] + subgroups}


# Overall
for tool in tqdm(all_models, desc="Overall"):
    subset = data[data[dna_models].notna().all(axis=1)]

    if subset["ClinVar_label"].nunique() < 2:
        results['Overall'][tool] = ""
        results_ci_low['Overall'][tool] = ""
        results_ci_high['Overall'][tool] = ""
        continue

    auc_hat, lo, hi = bootstrap_auc_ci(
        subset["ClinVar_label"], subset[tool]
    )

    if tool not in no_flip_models:
        auc_hat = 1 - auc_hat
        lo, hi = 1 - hi, 1 - lo

    results['Overall'][tool] = round(auc_hat, 4)
    results_ci_low['Overall'][tool] = round(lo, 4)
    results_ci_high['Overall'][tool] = round(hi, 4)

results['Overall']['#Variants'] = len(subset)
results_ci_low['Overall']['#Variants'] = ""
results_ci_high['Overall']['#Variants'] = ""
n_pos = subset["ClinVar_label"].sum() if len(subset) > 0 else 0
results['Overall']['p%'] = round(100 * n_pos / len(subset), 2) if len(subset) > 0 else ""
results_ci_low['Overall']['p%'] = ""
results_ci_high['Overall']['p%'] = ""


# Subgroups
for subgroup in tqdm(subgroups, desc="Subgroups"):

    required_models, tool_list = SUBGROUP_CONFIG[subgroup]

    subset = data[
        (data[required_models].notna().all(axis=1)) &
        (data[subgroup] == 1)
    ]

    total_variants = (data[subgroup] == 1).sum()
    n_pos = subset["ClinVar_label"].sum() if len(subset) > 0 else 0

    results[subgroup]['#Variants']         = len(subset)
    results_ci_low[subgroup]['#Variants']  = ""
    results_ci_high[subgroup]['#Variants'] = ""
    results[subgroup]['p%'] = (
        round(100 * n_pos / len(subset), 2) if len(subset) > 0 else ""
    )
    results_ci_low[subgroup]['p%']  = ""
    results_ci_high[subgroup]['p%'] = ""

    for tool in all_models:
        if tool not in tool_list:
            results[subgroup][tool] = ""
            results_ci_low[subgroup][tool] = ""
            results_ci_high[subgroup][tool] = ""
            continue

        if len(subset) == 0 or subset["ClinVar_label"].nunique() < 2:
            results[subgroup][tool] = ""
            results_ci_low[subgroup][tool] = ""
            results_ci_high[subgroup][tool] = ""
            continue

        auc_hat, lo, hi = bootstrap_auc_ci(
            subset["ClinVar_label"], subset[tool]
        )

        if tool not in no_flip_models:
            auc_hat = 1 - auc_hat
            lo, hi = 1 - hi, 1 - lo

        results[subgroup][tool] = round(auc_hat, 4)
        results_ci_low[subgroup][tool] = round(lo, 4)
        results_ci_high[subgroup][tool] = round(hi, 4)


# Export
df_result = pd.DataFrame(results)
df_low    = pd.DataFrame(results_ci_low)
df_high   = pd.DataFrame(results_ci_high)

display(df_result)

df_result.to_csv(TABLE_DIR / "figure_1_auroc.csv")
df_low.to_csv(TABLE_DIR / "figure_1_auroc_ci_low.csv")
df_high.to_csv(TABLE_DIR / "figure_1_auroc_ci_high.csv")

Overall:   0%|          | 0/17 [00:00<?, ?it/s]

Overall:   6%|▌         | 1/17 [00:35<09:27, 35.46s/it]

Overall:  12%|█▏        | 2/17 [01:13<09:16, 37.13s/it]

Overall:  18%|█▊        | 3/17 [01:51<08:45, 37.56s/it]

Overall:  24%|██▎       | 4/17 [02:21<07:25, 34.27s/it]

Overall:  29%|██▉       | 5/17 [02:42<05:57, 29.78s/it]

Overall:  35%|███▌      | 6/17 [03:14<05:34, 30.38s/it]

Overall:  41%|████      | 7/17 [03:53<05:31, 33.19s/it]

Overall:  47%|████▋     | 8/17 [04:33<05:17, 35.30s/it]

Overall:  53%|█████▎    | 9/17 [05:12<04:52, 36.52s/it]

Overall:  59%|█████▉    | 10/17 [05:52<04:22, 37.49s/it]

Overall:  65%|██████▍   | 11/17 [06:30<03:47, 37.91s/it]

Overall:  71%|███████   | 12/17 [06:43<02:31, 30.21s/it]

Overall:  76%|███████▋  | 13/17 [06:56<01:39, 24.86s/it]

Overall:  82%|████████▏ | 14/17 [07:08<01:03, 21.16s/it]

Overall:  88%|████████▊ | 15/17 [07:20<00:36, 18.43s/it]

Overall:  94%|█████████▍| 16/17 [07:30<00:15, 15.81s/it]

Overall: 100%|██████████| 17/17 [07:42<00:00, 14.54s/it]

Overall: 100%|██████████| 17/17 [07:42<00:00, 27.18s/it]

Subgroups:   0%|          | 0/15 [00:00<?, ?it/s]

Subgroups:   7%|▋         | 1/15 [03:16<45:48, 196.34s/it]

Subgroups:  13%|█▎        | 2/15 [06:16<40:27, 186.75s/it]

Subgroups:  20%|██        | 3/15 [06:23<20:54, 104.51s/it]

Subgroups:  27%|██▋       | 4/15 [07:26<16:11, 88.33s/it]

Subgroups:  33%|███▎      | 5/15 [07:36<10:01, 60.17s/it]

Subgroups:  40%|████      | 6/15 [08:00<07:09, 47.70s/it]

Subgroups:  47%|████▋     | 7/15 [08:06<04:34, 34.29s/it]

Subgroups:  53%|█████▎    | 8/15 [08:27<03:29, 29.97s/it]

Subgroups:  60%|██████    | 9/15 [10:42<06:15, 62.61s/it]

Subgroups:  67%|██████▋   | 10/15 [10:48<03:46, 45.33s/it]

Subgroups:  73%|███████▎  | 11/15 [12:22<04:00, 60.18s/it]

Subgroups:  80%|████████  | 12/15 [12:32<02:14, 44.99s/it]

Subgroups:  87%|████████▋ | 13/15 [12:43<01:09, 34.59s/it]

Subgroups:  93%|█████████▎| 14/15 [14:21<00:53, 53.85s/it]

Subgroups: 100%|██████████| 15/15 [14:32<00:00, 40.86s/it]

Subgroups: 100%|██████████| 15/15 [14:32<00:00, 58.17s/it]

,Overall,group: coding,group: noncoding,group: stop loss,group: synonymous,group: 5'UTR,group: 3'UTR,group: 3'UTR + RNA gene,group: splice,group: intron (non-splice),group: RNA gene,group: missense,group: missense + 3'UTR,group: missense + intron (non-splice),group: stop gain,group: start loss
PhyloP,0.9083,0.8358,0.9809,0.8165,0.8538,0.7026,0.8971,0.9375,0.7399,0.8473,0.8545,0.8694,0.8442,0.9314,0.6924,0.6679
Evo2_7B,0.9716,0.9466,0.9789,0.8523,0.8905,0.8079,0.8039,0.375,0.6971,0.8922,0.6402,0.8357,0.8692,0.8759,0.6546,0.7357
Evo2_40B,0.9733,0.9446,0.9856,0.7943,0.8942,0.8283,0.8779,0.9375,0.6644,0.9045,0.6706,0.8454,0.8567,0.8756,0.6259,0.7611
AlphaGenome_quantile,0.6908,0.5903,0.9934,0.3142,0.9364,0.5495,0.7945,0.9062,0.6176,0.9676,0.7566,0.5501,0.5821,0.5850,0.3965,0.5175
Rule_based,0.9713,0.9405,0.9548,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5000,0.5000,0.5000,0.5000,0.5
GPN_MSA,0.9617,0.9267,0.985,0.8972,0.8801,0.7605,0.9287,0.9375,0.774,0.8815,0.9484,0.9128,0.8400,0.9428,0.7777,0.7651
PhyloGPN,0.9579,0.9172,0.9794,0.7636,0.8673,0.7245,0.7468,0.625,0.8023,0.88,0.8042,0.8534,0.7183,0.8668,0.7506,0.7245
DNABERT2,0.4421,0.4416,0.466,0.5136,0.5996,0.3978,0.498,0.6875,0.4921,0.4716,0.4722,0.4937,0.5075,0.4747,0.4852,0.3942
ntv3_pre_position_llr,0.9073,0.9028,0.8843,0.6898,0.686,0.5451,0.6758,0.0625,0.5787,0.7522,0.6177,0.8264,0.7042,0.6841,0.6099,0.6361
ntv3_post_log2fc_max,0.7080,0.618,0.9764,0.6568,0.8161,0.5664,0.8083,0.625,0.6779,0.9072,0.7487,0.6000,0.4100,0.5333,0.5302,0.5068
gpnstar_v_llr,0.9735,0.9501,0.9877,0.8943,0.8965,0.7666,0.9304,1.0,0.8178,0.8957,0.9431,0.9312,0.8767,0.9536,0.7930,0.7618
ESM1b,0.9768,,,,,,,,,,,0.9316,0.9525,0.8842,0.7790,0.6825
ESM1v,0.9657,,,,,,,,,,,0.9018,0.9000,0.8263,0.6453,0.6323
ESM2,0.9677,,,,,,,,,,,0.8942,0.9567,0.8144,0.6791,0.7081
vesm_score,0.9842,,,,,,,,,,,0.9528,0.9392,0.9137,0.7135,0.6483
AlphaMissense,0.9866,,,,,,,,,,,0.9660,0.9392,0.9507,0.8317,
PrimateAI_3D,0.9847,,,,,,,,,,,0.9521,0.9433,0.9421,0.7991,
#Variants,241509.0000,125677,115832,62,39383,2379,11837,17,10170,86782,75,37076.0000,74.0000,208.0000,40567.0000,788
p%,28.7700,46.32,9.74,64.52,0.53,1.35,0.11,5.88,99.33,1.19,16.0,36.9600,32.4300,19.2300,99.6900,97.72

## 4. Render the manuscript figure

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from pathlib import Path
from collections import defaultdict
import numpy as np

FONT_SIZE = 8
FONT_NAME = 'DejaVu Sans'

SAVE_BIG = True

df      = pd.read_csv(TABLE_DIR / "figure_1_auroc.csv")
df_low  = pd.read_csv(TABLE_DIR / "figure_1_auroc_ci_low.csv")
df_high = pd.read_csv(TABLE_DIR / "figure_1_auroc_ci_high.csv")

# Apply post-processing corrections without recomputing
# 1. Remove auxiliary NTv3 score rows that are not shown in the figure.
for _df in [df, df_low, df_high]:
    _df.drop(_df[~_df["Unnamed: 0"].isin(['ntv3_pre_seq_pllr', 'ntv3_post_position_llr', 'ntv3_post_seq_pllr']) == False].index,
             inplace=True)

# 2. Set protein-model values to NaN in the overall panel before renaming
protein_models_overall = [
    "ESM1b", "ESM1v", "ESM2", "AlphaMissense", "PrimateAI_3D", "vesm_score"
]
for pm in protein_models_overall:
    for _df in [df, df_low, df_high]:
        _df.loc[_df["Unnamed: 0"] == pm, "Overall"] = np.nan

# Rename
rename_dict = {
    "Evo2_7B":              "Evo2 7B",
    "Evo2_40B":             "Evo2 40B",
    "DNABERT2":             "DNABERT2",
    "PhyloP":               "PhyloP",
    "AlphaGenome_quantile": "AlphaGenome",
    "GPN_MSA":              "GPN-MSA",
    "PhyloGPN":             "PhyloGPN",
    "ESM1b":                "ESM1b",
    "ESM1v":                "ESM1v",
    "ESM2":                 "ESM2",
    "PrimateAI_3D":         "PrimateAI-3D",
    "AlphaMissense":        "AlphaMissense",
    "Rule_based":           "Rule-based",
    "vesm_score":           "VESM++",
    "gpnstar_v_llr":        "GPN-Star",
    "ntv3_pre_position_llr": "NTv3-pre",
    "ntv3_post_log2fc_max": "NTv3-post"
}

for _df in [df, df_low, df_high]:
    _df.rename(columns=rename_dict, inplace=True)
    _df["Unnamed: 0"] = _df["Unnamed: 0"].replace(rename_dict)

# Palette
palette = {
    "Evo2 7B":          "#e56b6f",
    "Evo2 40B":         "#c93735",
    "DNABERT2":         "#1b78b2",
    "NTv3-pre":         "#6baed6",
    "NTv3-pre PLLR":    "#4292c6",
    "NTv3-post LLR":    "#2171b5",
    "NTv3-post PLLR":   "#084594",
    "NTv3-post":        "#54278f",
    "GPN-Star":         "#20b2aa",
    "PhyloP":           "#808080",
    "GPN-MSA":          "#859ed7",
    "PhyloGPN":         "#f47f1e",
    "AlphaGenome":      "#a2d94d",
    "ESM1b":            "#2da248",
    "ESM1v":            "#8f69c5",
    "ESM2":             "#22bdd2",
    "VESM++":           "#e377c2",
    "PrimateAI-3D":     "#d26101",
    "AlphaMissense":    "#333a8c",
    "Rule-based":       "#b0b0b0",
}

# Hatch protein-model bars; leave DNA-model bars solid
dashed_models = ["ESM1b", "ESM1v", "ESM2", "AlphaMissense", "PrimateAI-3D", "VESM++"]

model_rows     = df["Unnamed: 0"].tolist()[:-2]
df_models      = df[df["Unnamed: 0"].isin(model_rows)].set_index("Unnamed: 0")
df_low_models  = df_low[df_low["Unnamed: 0"].isin(model_rows)].set_index("Unnamed: 0")
df_high_models = df_high[df_high["Unnamed: 0"].isin(model_rows)].set_index("Unnamed: 0")

n_row = df[df["Unnamed: 0"] == "#Variants"].iloc[0]
p_row = df[df["Unnamed: 0"] == "p%"].iloc[0]

display_map = {
    "Overall":                               "All variants",
    "group: noncoding":                      "Noncoding",
    "group: intron (non-splice)":            "Intron (Non-splice)",
    "group: splice":                         "Splice",
    "group: 5'UTR":                          "5' UTR",
    "group: 3'UTR":                          "3' UTR",
    "group: RNA gene":                       "RNA gene",
    "group: synonymous":                     "Synonymous",
    "group: start loss":                     "Start loss",
    "group: stop loss":                      "Stop loss",
    "group: missense":                       "Missense",
    "group: missense + intron (non-splice)": "Missense & Intron (Non-splice)",
    "group: missense + 3'UTR":               "Missense & 3'UTR",
    "group: stop gain":                      "Stop gain",
}

ordered_display_names = [
    "All variants", "Noncoding", "Intron (Non-splice)", "Splice", "3' UTR", "5' UTR",
    "RNA gene", "Synonymous", "Stop loss", "Start loss",
    "Missense", "Missense & Intron (Non-splice)", "Missense & 3'UTR", "Stop gain"
]

reverse_display_map = {v: k for k, v in display_map.items()}

group_values = defaultdict(list)
for raw_k, disp_k in display_map.items():
    if raw_k in df_models.columns:
        for model in df_models.index:
            val = df_models.at[model, raw_k]
            if pd.notna(val) and val != "":
                group_values[raw_k].append((model, float(val)))


def style_axes(ax, show_xlabel=False, show_numbers=False):
    ax.set_xlim(0.5, 1.03)
    ax.xaxis.set_major_locator(ticker.MultipleLocator(0.1))
    xticks = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    ax.set_xticks(xticks)
    ax.tick_params(axis='x', which='major', bottom=True, width=0.5, length=3.0)
    if show_numbers:
        ax.set_xticklabels([f"{t:.1f}" for t in xticks],
                           fontsize=FONT_SIZE, fontname=FONT_NAME)
        ax.tick_params(axis='x', labelbottom=True)
    else:
        ax.tick_params(axis='x', labelbottom=False)
    if show_xlabel:
        ax.set_xlabel("AUROC", fontsize=FONT_SIZE, fontname=FONT_NAME)
    ax.tick_params(axis='y', which='major', left=True, labelleft=True,
                   width=0.5, length=3.0)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_linewidth(0.5)
    ax.spines['left'].set_linewidth(0.5)
    ax.tick_params(labelsize=FONT_SIZE)
    for label in ax.get_yticklabels():
        label.set_fontname(FONT_NAME)


def draw_one_panel(ax, raw_key, display_name, show_xlabel=False, show_numbers=False):
    values = group_values[raw_key]
    if display_name not in ["All variants", "Noncoding"]:
        values = [(m, auc) for m, auc in values if m != "Rule-based"]

    rows = sorted(values, key=lambda x: x[1])

    n = int(float(n_row[raw_key]))
    p = float(p_row[raw_key]) / 100

    too_few     = (n * p < 10 or n * (1 - p) < 10)
    panel_alpha = 0.3 if too_few else 1.0

    x_pad = 0.006

    for model, auc in rows:
        color       = palette.get(model, "#333333")
        hatch_style = '///' if model in dashed_models else None

        ax.barh(
            model, auc,
            color=color,
            hatch=hatch_style,
            edgecolor='white' if hatch_style else None,
            linewidth=0.6,
            alpha=panel_alpha,
        )

        lo = hi = np.nan
        try:
            lo = df_low_models.at[model, raw_key]
            hi = df_high_models.at[model, raw_key]
        except Exception:
            lo, hi = np.nan, np.nan

        has_ci = (pd.notna(lo) and pd.notna(hi) and lo != "" and hi != "")
        if has_ci:
            lo = float(lo); hi = float(hi)
            lo = max(0.0, min(1.0, lo))
            hi = max(0.0, min(1.0, hi))
            has_ci = (hi >= lo)

        if auc < 0.5:
            ax.text(
                0.505, model, f"{auc:.3f}",
                va='center', ha='left',
                fontsize=FONT_SIZE, fontname=FONT_NAME, alpha=panel_alpha,
            )
            continue

        if has_ci:
            ax.errorbar(
                x=auc, y=model,
                xerr=[[auc - lo], [hi - auc]],
                fmt='none',
                ecolor='black',
                elinewidth=0.8,
                capsize=2,
                capthick=0.8,
                zorder=10,
                alpha=panel_alpha,
            )
            x_anchor = max(auc, hi)
        else:
            x_anchor = auc

        x_text = min(x_anchor + x_pad, ax.get_xlim()[1] - 0.002)
        ax.text(
            x_text, model, f"{auc:.3f}",
            va='center', ha='left',
            fontsize=FONT_SIZE, fontname=FONT_NAME
        )

    ax.set_title(
        f"{display_name} (N={n:,}, %P={p*100:.2f}%)",
        fontsize=FONT_SIZE, fontname=FONT_NAME, fontweight="bold"
    )
    style_axes(ax, show_xlabel=show_xlabel, show_numbers=show_numbers)
    return True


fig, axes = plt.subplots(nrows=5, ncols=3, figsize=(12, 16), dpi=300)
axes = axes.T.flatten()

for i, disp_name in enumerate(ordered_display_names):
    col = i // 5
    row = i % 5
    show_xlabel  = (col == 0 and row == 4) or (col == 1 and row == 4) or (col == 2 and row == 3)
    show_numbers = show_xlabel
    draw_one_panel(
        axes[i],
        reverse_display_map[disp_name],
        disp_name,
        show_xlabel=show_xlabel,
        show_numbers=show_numbers,
    )

axes[-1].axis('off')

plt.tight_layout()
if SAVE_BIG:
    plt.savefig(FIGURE_DIR / "figure_1.svg", format="svg", bbox_inches="tight")
plt.show()

## 5. Validate outputs

In [8]:

validate_output_files([
    TABLE_DIR / "figure_1_auroc.csv",
    TABLE_DIR / "figure_1_auroc_ci_low.csv",
    TABLE_DIR / "figure_1_auroc_ci_high.csv",
    FIGURE_DIR / "figure_1.svg",
])

Validated 4 output file(s).